name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'
        
    - name: Install Dependencies
      run: flutter packages get
    - name: Format Code
      run: dart format --set-exit-if-changed .
    - name: Analyze Code
      run: flutter analyze .
    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

    - uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
